[project]
name = 'create-eclipse-space'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.create-eclipse-space]
path = 'contracts/create-eclipse-space.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
